/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasbihRouteImport } from './routes/tasbih'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as PrayerTimesRouteImport } from './routes/prayer-times'
import { Route as HadithRouteImport } from './routes/hadith'
import { Route as DuasRouteImport } from './routes/duas'
import { Route as AdhkarRouteImport } from './routes/adhkar'
import { Route as IndexRouteImport } from './routes/index'

const TasbihRoute = TasbihRouteImport.update({
  id: '/tasbih',
  path: '/tasbih',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerTimesRoute = PrayerTimesRouteImport.update({
  id: '/prayer-times',
  path: '/prayer-times',
  getParentRoute: () => rootRouteImport,
} as any)
const HadithRoute = HadithRouteImport.update({
  id: '/hadith',
  path: '/hadith',
  getParentRoute: () => rootRouteImport,
} as any)
const DuasRoute = DuasRouteImport.update({
  id: '/duas',
  path: '/duas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdhkarRoute = AdhkarRouteImport.update({
  id: '/adhkar',
  path: '/adhkar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adhkar': typeof AdhkarRoute
  '/duas': typeof DuasRoute
  '/hadith': typeof HadithRoute
  '/prayer-times': typeof PrayerTimesRoute
  '/radio': typeof RadioRoute
  '/tasbih': typeof TasbihRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adhkar': typeof AdhkarRoute
  '/duas': typeof DuasRoute
  '/hadith': typeof HadithRoute
  '/prayer-times': typeof PrayerTimesRoute
  '/radio': typeof RadioRoute
  '/tasbih': typeof TasbihRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adhkar': typeof AdhkarRoute
  '/duas': typeof DuasRoute
  '/hadith': typeof HadithRoute
  '/prayer-times': typeof PrayerTimesRoute
  '/radio': typeof RadioRoute
  '/tasbih': typeof TasbihRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adhkar'
    | '/duas'
    | '/hadith'
    | '/prayer-times'
    | '/radio'
    | '/tasbih'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adhkar'
    | '/duas'
    | '/hadith'
    | '/prayer-times'
    | '/radio'
    | '/tasbih'
  id:
    | '__root__'
    | '/'
    | '/adhkar'
    | '/duas'
    | '/hadith'
    | '/prayer-times'
    | '/radio'
    | '/tasbih'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdhkarRoute: typeof AdhkarRoute
  DuasRoute: typeof DuasRoute
  HadithRoute: typeof HadithRoute
  PrayerTimesRoute: typeof PrayerTimesRoute
  RadioRoute: typeof RadioRoute
  TasbihRoute: typeof TasbihRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasbih': {
      id: '/tasbih'
      path: '/tasbih'
      fullPath: '/tasbih'
      preLoaderRoute: typeof TasbihRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer-times': {
      id: '/prayer-times'
      path: '/prayer-times'
      fullPath: '/prayer-times'
      preLoaderRoute: typeof PrayerTimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hadith': {
      id: '/hadith'
      path: '/hadith'
      fullPath: '/hadith'
      preLoaderRoute: typeof HadithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duas': {
      id: '/duas'
      path: '/duas'
      fullPath: '/duas'
      preLoaderRoute: typeof DuasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adhkar': {
      id: '/adhkar'
      path: '/adhkar'
      fullPath: '/adhkar'
      preLoaderRoute: typeof AdhkarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdhkarRoute: AdhkarRoute,
  DuasRoute: DuasRoute,
  HadithRoute: HadithRoute,
  PrayerTimesRoute: PrayerTimesRoute,
  RadioRoute: RadioRoute,
  TasbihRoute: TasbihRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
