/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasbihRouteImport } from './routes/tasbih'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as QuranReadRouteImport } from './routes/quran-read'
import { Route as QuranListenRouteImport } from './routes/quran-listen'
import { Route as PrayerTimesRouteImport } from './routes/prayer-times'
import { Route as HadithRouteImport } from './routes/hadith'
import { Route as DuasRouteImport } from './routes/duas'
import { Route as AdhkarRouteImport } from './routes/adhkar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuranReadSurahRouteImport } from './routes/quran-read.$surah'

const TasbihRoute = TasbihRouteImport.update({
  id: '/tasbih',
  path: '/tasbih',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranReadRoute = QuranReadRouteImport.update({
  id: '/quran-read',
  path: '/quran-read',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranListenRoute = QuranListenRouteImport.update({
  id: '/quran-listen',
  path: '/quran-listen',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerTimesRoute = PrayerTimesRouteImport.update({
  id: '/prayer-times',
  path: '/prayer-times',
  getParentRoute: () => rootRouteImport,
} as any)
const HadithRoute = HadithRouteImport.update({
  id: '/hadith',
  path: '/hadith',
  getParentRoute: () => rootRouteImport,
} as any)
const DuasRoute = DuasRouteImport.update({
  id: '/duas',
  path: '/duas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdhkarRoute = AdhkarRouteImport.update({
  id: '/adhkar',
  path: '/adhkar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranReadSurahRoute = QuranReadSurahRouteImport.update({
  id: '/$surah',
  path: '/$surah',
  getParentRoute: () => QuranReadRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adhkar': typeof AdhkarRoute
  '/duas': typeof DuasRoute
  '/hadith': typeof HadithRoute
  '/prayer-times': typeof PrayerTimesRoute
  '/quran-listen': typeof QuranListenRoute
  '/quran-read': typeof QuranReadRouteWithChildren
  '/radio': typeof RadioRoute
  '/stories': typeof StoriesRoute
  '/tasbih': typeof TasbihRoute
  '/quran-read/$surah': typeof QuranReadSurahRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adhkar': typeof AdhkarRoute
  '/duas': typeof DuasRoute
  '/hadith': typeof HadithRoute
  '/prayer-times': typeof PrayerTimesRoute
  '/quran-listen': typeof QuranListenRoute
  '/quran-read': typeof QuranReadRouteWithChildren
  '/radio': typeof RadioRoute
  '/stories': typeof StoriesRoute
  '/tasbih': typeof TasbihRoute
  '/quran-read/$surah': typeof QuranReadSurahRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adhkar': typeof AdhkarRoute
  '/duas': typeof DuasRoute
  '/hadith': typeof HadithRoute
  '/prayer-times': typeof PrayerTimesRoute
  '/quran-listen': typeof QuranListenRoute
  '/quran-read': typeof QuranReadRouteWithChildren
  '/radio': typeof RadioRoute
  '/stories': typeof StoriesRoute
  '/tasbih': typeof TasbihRoute
  '/quran-read/$surah': typeof QuranReadSurahRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adhkar'
    | '/duas'
    | '/hadith'
    | '/prayer-times'
    | '/quran-listen'
    | '/quran-read'
    | '/radio'
    | '/stories'
    | '/tasbih'
    | '/quran-read/$surah'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adhkar'
    | '/duas'
    | '/hadith'
    | '/prayer-times'
    | '/quran-listen'
    | '/quran-read'
    | '/radio'
    | '/stories'
    | '/tasbih'
    | '/quran-read/$surah'
  id:
    | '__root__'
    | '/'
    | '/adhkar'
    | '/duas'
    | '/hadith'
    | '/prayer-times'
    | '/quran-listen'
    | '/quran-read'
    | '/radio'
    | '/stories'
    | '/tasbih'
    | '/quran-read/$surah'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdhkarRoute: typeof AdhkarRoute
  DuasRoute: typeof DuasRoute
  HadithRoute: typeof HadithRoute
  PrayerTimesRoute: typeof PrayerTimesRoute
  QuranListenRoute: typeof QuranListenRoute
  QuranReadRoute: typeof QuranReadRouteWithChildren
  RadioRoute: typeof RadioRoute
  StoriesRoute: typeof StoriesRoute
  TasbihRoute: typeof TasbihRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasbih': {
      id: '/tasbih'
      path: '/tasbih'
      fullPath: '/tasbih'
      preLoaderRoute: typeof TasbihRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran-read': {
      id: '/quran-read'
      path: '/quran-read'
      fullPath: '/quran-read'
      preLoaderRoute: typeof QuranReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran-listen': {
      id: '/quran-listen'
      path: '/quran-listen'
      fullPath: '/quran-listen'
      preLoaderRoute: typeof QuranListenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer-times': {
      id: '/prayer-times'
      path: '/prayer-times'
      fullPath: '/prayer-times'
      preLoaderRoute: typeof PrayerTimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hadith': {
      id: '/hadith'
      path: '/hadith'
      fullPath: '/hadith'
      preLoaderRoute: typeof HadithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duas': {
      id: '/duas'
      path: '/duas'
      fullPath: '/duas'
      preLoaderRoute: typeof DuasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adhkar': {
      id: '/adhkar'
      path: '/adhkar'
      fullPath: '/adhkar'
      preLoaderRoute: typeof AdhkarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran-read/$surah': {
      id: '/quran-read/$surah'
      path: '/$surah'
      fullPath: '/quran-read/$surah'
      preLoaderRoute: typeof QuranReadSurahRouteImport
      parentRoute: typeof QuranReadRoute
    }
  }
}

interface QuranReadRouteChildren {
  QuranReadSurahRoute: typeof QuranReadSurahRoute
}

const QuranReadRouteChildren: QuranReadRouteChildren = {
  QuranReadSurahRoute: QuranReadSurahRoute,
}

const QuranReadRouteWithChildren = QuranReadRoute._addFileChildren(
  QuranReadRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdhkarRoute: AdhkarRoute,
  DuasRoute: DuasRoute,
  HadithRoute: HadithRoute,
  PrayerTimesRoute: PrayerTimesRoute,
  QuranListenRoute: QuranListenRoute,
  QuranReadRoute: QuranReadRouteWithChildren,
  RadioRoute: RadioRoute,
  StoriesRoute: StoriesRoute,
  TasbihRoute: TasbihRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
